system :
    mode : "tr" # "si" : run SPH simulations, "ad" : analyze data, "tr" : train ML model, "dr" : download ML results, "ar" : analyze ML results, "am" : analyze ML model

    # supported GPU architecture options (only required for data generation):
    # "sm_20": GTX570, Quadro4000
    # "sm_35": GTX Titan, Kepler K40
    # "sm_37": Kepler K80
    # "sm_52": GTX970, GTX TitanX
    # "sm_50": GTX750 Ti
    # "sm_30": GTX680 and GTX770
    # "sm_61": GTX1080, GTX1070, GTX1060, GTX1050, GTX1030, Titan Xp, Tesla P40, Tesla P4
    local :
        path_project : "/home/philip/Documents/projects/19_CSV/" # project path
        gpu_arch : "sm_61" # GTX1060
    server:
        path_project : "/system/user/winter/Documents/projects/19_CSV/" # project path
        gpu_arch : "sm_61" # GTX1080

SPH :
    system :
        local:
            path_Astro_SPH : "/mnt/data/input/Astro_SPH/" # data path
        server:
            path_Astro_SPH : "/system/user/publicdata/Astro_SPH/" # data path
         
    sim :
        setup_type : "custom" # "random": run many random setups, "custom": run one specific setup
        
        random_setup :  # official parameter space
            cleanup : true
            subsampling : 10 # frames that are kept are subsampled to reduce memory footprint
            n_simulations : 1000 # number of simulations to perform for each program execution
            checkpoint : 0 # specify where to continue pipeline
            checkpoint_ID : "r216194367924831" # for debugging
            t_sim_fact_min : 40. # t_sim = round_up(collision_timescale * (t_sim_fact + ini_dist_fact))
            t_sim_fact_max : 60.
            ini_dist_fact_min : 3. # objects are placed at ini_dist_fact*sum(radii) distance to each other (default: 5.)
            ini_dist_fact_max : 7.
            n_frames : 1 # number of SPH output frames per hour
            frame_interval : 5 # use every frame_interval SPH output frames for in-depth analysis
            N_min : 20000 # min number of SPH particles (C. Burger Diss: N=10k, mat_fraction_min=0.1 --> water shell thickness ~2 SPH particles)
            N_max : 50000 # max number of SPH particles
            M_tot_min : 1.8786e+21 # [kg], minimum total mass = 2 * m_ceres
            M_tot_max : 1.19444e+25 # [kg], maximum total mass = 2 * m_earth
            gamma_min : 0.05 # minimum mass ratio projectile / target
            gamma_max : 1. # maximum mass ratio projectile / target
            iron_fraction_min : 0.01
            iron_fraction_max : 0.25
            water_fraction_min : 0.
            water_fraction_max : 0.25
            vel_vesc_min : 1. # minimum impact velocity [v_esc]
            vel_vesc_max : 8. # maximum impact velocity [v_esc]
            impact_angle_min : 0. # minimum impact angle [deg]
            impact_angle_max : 90. # maximum impact angle [deg] (0: head-on, 90: grazing)
            rot_limit : 0.2 # maximum rotation period [T_crit]
            n_sph_min : 5 # minimum number of SPH particles in a "large" fragment
        
        custom_setup :
            cleanup : false
            subsampling : 1 # frames that are kept are subsampled to reduce memory footprint
            n_simulations : 1
            checkpoint : 2 # specify where to continue pipeline
            checkpoint_ID : "c751716852135381"
            t_sim_fact : 46.353905697556435 # t_sim = round_up(collision_timescale * (t_sim_fact + ini_dist_fact))
            ini_dist_fact : 5.724389609341498 # objects are placed at ini_dist_fact*sum(radii) distance to each other (default: 5.)
            n_frames : 100 # number of SPH output frames per hour
            frame_interval : 1 # use every frame_interval SPH output frames for in-depth analysis
            N : 46063 # number of SPH particles
            M_tot : 4.69042151982061e+24 # total mass [kg]
            M_proj : 4.270318941988767e+23
            n_mat : 3
            core_mat : "Iron"
            mantle_mat : "BasaltNakamura"
            shell_mat : "Water"
            f_m_key : "iron_basalt_water"
            mantle_proj : 0.651819507941678
            shell_proj : 0.230434416535625
            mantle_targ : 0.9732447416577706
            shell_targ : 0.
            proj_rot_axis_x : -73589.20039119 # rotation axes
            proj_rot_axis_y : 196060.43410405
            proj_rot_axis_z : 333162.52599519
            targ_rot_axis_x : -26406.35085322
            targ_rot_axis_y : -25264.02199751
            targ_rot_axis_z : -35302.93138828
            proj_rot_period : 393512.81168822985
            targ_rot_period : 50812.0373285658
            vel_vesc_touching_ball : 1.3362676465300636 # impact velocity [v_esc]
            impact_angle_touching_ball : 42.88870918586685 # impact angle [deg]
            n_sph_min : 5 # minimum number of SPH particles in a "large" fragment

ML :
    system :
        run : 0  # experiment ID (CAUTION: existing directories will be overwritten)
        dir_check_local : '/mnt/data/output/19_CSV/'
        dir_check_server : '/system/user/publicwork/winter/output/19_CSV/'
        dir_analyze_local : '/mnt/data/output/19_CSV/'
        dir_analyze_server : '/system/user/publicwork/winter/output/19_CSV/'

    dataset :
        name : "winter" # "winter", "timpe"
        shuffle : true  # for dataloader. default: true
        num_workers : 4  # for dataloader. default: 4
        winter :
            path_local : "/mnt/data/input/Astro_SPH/csv/"
            path_server : "/system/user/publicdata/Astro_SPH/csv/"
            n_samples_max : 12000 # maximum number of samples to use from data. default: 12000
            n_frames_nonzero_max : 12  # maximum number of frames to use from data. default: 12
            n_frag_large_max : 8  # maximum number of large fragments to use from data. default: 8
            augmentation : False  # data augmentation (random rotation). optional rotation module will be used for models. default: False
            inputs : "setup"  # "setup"
            targets : "agg"  # "agg"
            n_x_setup : 25  # number of input features
            n_z_agg : 27  # number of target features
        timpe:
            path_local: "/mnt/data/input/Astro_SPH/timpe/doi_10.5061_dryad.j6q573n94__v2/"
            path_server: "/system/user/publicdata/Astro_SPH/timpe/doi_10.5061_dryad.j6q573n94__v2/"
            n_x: 25  # number of input features
            n_z: 27  # number of target features
        analysis :
            mode : "stewart"  # "gather_all", "filter", "stewart", "invalid"
            path_local : "/mnt/data/input/Astro_SPH/analysis/"
            path_server : "/system/user/publicdata/Astro_SPH/analysis/"
        
    model :
        type : "res"  # select ML model to use. options: pm, linear, ffn, res
        save : True  # save model after last epoch. default: True
        ffn :
            n_h : 56  # default: 56
            n_l : 8  # default: 8
        res:
            s_h: 4  # specify how many steps in model correspond to t=1 hour. default: 4
            first: 1 # 0: predicted sequence y starts with frame 0000, 1: predicted sequence y starts with frame 0001. default: 1
            n_h: 64  # number of hidden units per block. default: 64
            n_l: 3  # number of layers per block. default: 3
            reg_drift: True  # regularize hidden units. default: True
            reg_drift_lim: 2.  # penalize hidden activations that are smaller than -reg_drift_lim or larger than reg_drift_lim. default: 2.

    training :
        mode : "last_frame"  # specify if all frames or only last frame is used for training. options: "last_frame", "all_frames". default: last_frame
        loss_fn : "ae"  # ae, se, ae_mass, ae_mat, ae_pos, ae_vel, ae_mass_mat, ae_pos_vel, ae_mass_mat_pos
        training_data_amount : 1  # if < 1: using less training data. default: 1
        verbosity : 40 # evaluation interval in epochs. default: 40
        split_method : 1 # options for data splits: 0: classic, 1: crossvalidation, ood test split (manually selected regions), 2: crossvalidation, iid test split, 3: train on entire development set (train + vali data)
        folds : 5 # number of crossvalidation folds. default: 5
        epochs : 5000 # number of epochs per fold. default: 5000 (2000 for timpe)
        bs : 128 # minibatch size. default: 128
        weight_decay : 0.0001  # default: 0.0001
        optimizer : "adamax"  # SGD, adamax
        lr : 0.0005 # learning rate. default: 0.0005
        momentum : 0.9
        beta1 : 0.9
        beta2 : 0.9
        grad_clip_type : "norm"  # gradient clipping options: norm, value, none. default: norm
        grad_clip : 50.  # maximum value for gradient clipping. default: 50
        rate_ema : 0.999  # exponential moving average model rate. default: 0.999

    analysis :
        dir_analyze_local : '/mnt/data/output/19_CSV/'
        dir_analyze_server : '/mnt/data/output/download/19_CSV/'
        fontsize : 12  # matplotlib fontsize